baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Brown & Greiss Planning Strategies'

[build]
  writeStats = true

[build.buildStats]
  enable = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

[markup]
  [markup.highlight]
    noClasses = false

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']

[build.mounts]
  source = "assets"
  target = "assets"

[[module.imports]]
  path = "github.com/gohugoio/hugo-mod-heroicons"

theme = ['hugo-shortcode-roneo-collection', 'bgaps-hugo']
